// ゴジラずかん v7 - ゴジラ22体 + 怪獣29体 = 51体 + 鳴き声タイプ
const KAIJU_DATA = [
  // === ゴジラのバリエーション (22) ===
  { id:"showa-1954", type:"godzilla", roar:"godzilla", name:"しょだいゴジラ", fullName:"初代ゴジラ", year:1954, era:"しょうわ", height:50, weight:20000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"いちばん さいしょの ゴジラ。くろくて おっきいよ。", likes:"げんしりょく", weak:"オキシジェンデストロイヤー", funFact:"うまれてから70ねん！", color:"#2a2a2a", relatedIds:[] },
  { id:"showa-kingkong", type:"godzilla", roar:"godzilla", name:"VSキングコング", fullName:"キングコング対ゴジラ", year:1962, era:"しょうわ", height:50, weight:20000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"おおきな ゴリラの キングコングと たたかった ゴジラ。", likes:"おにく", weak:"でんき", funFact:"ふじさんで たたかったよ！", color:"#3d2817", relatedIds:["kingkong"] },
  { id:"showa-mothra", type:"godzilla", roar:"godzilla", name:"VSモスラ", fullName:"モスラ対ゴジラ", year:1964, era:"しょうわ", height:50, weight:20000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"やさしい がの モスラと たたかった ゴジラ。", likes:"ぼうりょく", weak:"りんぷん", funFact:"モスラに まけたよ", color:"#4a5a2a", relatedIds:["mothra"] },
  { id:"showa-ghidorah", type:"godzilla", roar:"godzilla", name:"VSキングギドラ", fullName:"三大怪獣 地球最大の決戦", year:1964, era:"しょうわ", height:50, weight:20000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"うちゅうの りゅう、キングギドラと はじめて たたかった！", likes:"ともだち", weak:"ひとりぼっち", funFact:"モスラと ラドンと チームになったよ", color:"#5a4a1a", relatedIds:["king-ghidorah","mothra","rodan"] },
  { id:"showa-hedora", type:"godzilla", roar:"godzilla", name:"VSヘドラ", fullName:"ゴジラ対ヘドラ", year:1971, era:"しょうわ", height:50, weight:20000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"こうがいで できた ヘドラと たたかった ゴジラ。", likes:"きれいな くうき", weak:"どろどろ", funFact:"そらを とんだ ゴジラだよ！", color:"#4a3a4a", relatedIds:["hedorah"] },
  { id:"showa-mechagodzilla", type:"godzilla", roar:"godzilla", name:"VSメカゴジラ", fullName:"メカゴジラの逆襲", year:1975, era:"しょうわ", height:50, weight:20000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"ロボットの メカゴジラと たたかった ゴジラ。", likes:"ほんとうの ちから", weak:"ミサイル", funFact:"アンギラスと チームになった！", color:"#3a3a4a", relatedIds:["mechagodzilla","anguirus"] },
  { id:"heisei-1984", type:"godzilla", roar:"godzilla", name:"へいせいゴジラ", fullName:"ゴジラ（1984）", year:1984, era:"へいせい", height:80, weight:50000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"ひさしぶりに かえってきた ゴジラ。おおきく なったよ。", likes:"げんしりょく", weak:"カドミウム", funFact:"30メートルも おおきく なった！", color:"#2c4a2c", relatedIds:[] },
  { id:"heisei-biollante", type:"godzilla", roar:"godzilla", name:"VSビオランテ", fullName:"ゴジラvsビオランテ", year:1989, era:"へいせい", height:80, weight:50000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"おはなの かいじゅう ビオランテと たたかった。", likes:"たたかい", weak:"バクテリア", funFact:"ビオランテは ゴジラの ばらから うまれた", color:"#3d5a2c", relatedIds:["biollante"] },
  { id:"heisei-ghidorah", type:"godzilla", roar:"godzilla", name:"VSキングギドラ（へいせい）", fullName:"ゴジラvsキングギドラ", year:1991, era:"へいせい", height:100, weight:60000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"もういっかい キングギドラと たたかった ゴジラ。", likes:"おおきく なること", weak:"メカキングギドラ", funFact:"100メートルに おおきく なった！", color:"#4a3a1a", relatedIds:["king-ghidorah"] },
  { id:"heisei-mothra", type:"godzilla", roar:"godzilla", name:"VSモスラ（へいせい）", fullName:"ゴジラvsモスラ", year:1992, era:"へいせい", height:100, weight:60000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"へいせいの モスラと たたかった ゴジラ。", likes:"ねつせん", weak:"ふたごの モスラ", funFact:"モスラと バトラの 2ひきが あいて！", color:"#4a5a2a", relatedIds:["mothra","battra"] },
  { id:"heisei-mechagodzilla", type:"godzilla", roar:"godzilla", name:"VSメカゴジラ（へいせい）", fullName:"ゴジラvsメカゴジラ", year:1993, era:"へいせい", height:100, weight:60000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"あたらしい メカゴジラと たたかった ゴジラ。", likes:"ベビーゴジラ", weak:"Gフォース", funFact:"ベビーゴジラと いっしょ！", color:"#4a4a5a", relatedIds:["mechagodzilla"] },
  { id:"heisei-spacegodzilla", type:"godzilla", roar:"godzilla", name:"VSスペースゴジラ", fullName:"ゴジラvsスペースゴジラ", year:1994, era:"へいせい", height:100, weight:60000, skill:"ねつせんビーム", skillReading:"ねつせんびーむ", description:"うちゅうから きた スペースゴジラと たたかった。", likes:"リトルゴジラ", weak:"クリスタル", funFact:"じぶんの コピーと たたかった！", color:"#3a2a5a", relatedIds:["space-godzilla"] },
  { id:"burning-godzilla", type:"godzilla", roar:"godzilla-burning", name:"バーニングゴジラ", fullName:"ゴジラvsデストロイア", year:1995, era:"へいせい", height:100, weight:60000, skill:"あかいねつせん", skillReading:"あかいねつせん", description:"からだじゅう まっかに もえてる ゴジラ！", likes:"ねつ", weak:"メルトダウン", funFact:"もえつきて しんでしまった ゴジラ", color:"#8a1a1a", relatedIds:["destoroyah"] },
  { id:"hollywood-1998", type:"godzilla", roar:"zilla", name:"ハリウッドゴジラ", fullName:"GODZILLA（1998）", year:1998, era:"ハリウッド", height:55, weight:20000, skill:"おおきな くちで かみつく", skillReading:"おおきなくちでかみつく", description:"アメリカで つくられた ほそい ゴジラ。はやく うごくよ。", likes:"さかな", weak:"ミサイル", funFact:"あとで ジラに なまえが かわった", color:"#2a3a4a", relatedIds:["zilla"] },
  { id:"millennium-2000", type:"godzilla", roar:"godzilla", name:"ミレニアムゴジラ", fullName:"ゴジラ2000 ミレニアム", year:1999, era:"ミレニアム", height:55, weight:25000, skill:"むらさきねつせん", skillReading:"むらさきねつせん", description:"せなかの とげが むらさきの ゴジラ。", likes:"オルガと たたかうこと", weak:"オルガ", funFact:"21せいきの さいしょの ゴジラ！", color:"#3a2a4a", relatedIds:["orga"] },
  { id:"final-wars", type:"godzilla", roar:"godzilla", name:"ファイナルウォーズ", fullName:"ゴジラ ファイナルウォーズ", year:2004, era:"ミレニアム", height:100, weight:55000, skill:"あかいねつせん", skillReading:"あかいねつせん", description:"せかいじゅうの かいじゅうと たたかった ゴジラ！", likes:"ぼうそう", weak:"ミニラ", funFact:"10ぴき いじょうの かいじゅうを やっつけた！", color:"#3a4a2a", relatedIds:["minilla","gigan","anguirus","rodan","mothra","ebirah","kumonga","zilla"] },
  { id:"hollywood-2014", type:"godzilla", roar:"godzilla-modern", name:"ハリウッドゴジラ（2014）", fullName:"GODZILLA（2014）", year:2014, era:"モンスターバース", height:108, weight:90000, skill:"あおいねつせん", skillReading:"あおいねつせん", description:"あたらしい ハリウッドの ゴジラ。とっても おっきいよ。", likes:"うみで およぐこと", weak:"むね", funFact:"ムートーと たたかったよ！", color:"#2a3a3a", relatedIds:["muto"] },
  { id:"shin-godzilla", type:"godzilla", roar:"shin-godzilla", name:"シン・ゴジラ", fullName:"シン・ゴジラ", year:2016, era:"レイワ", height:118, weight:92000, skill:"ぜんしんから ビーム", skillReading:"ぜんしんからびーむ", description:"へんしんする ゴジラ。からだが あかく ひかるよ。", likes:"しんか", weak:"けつえき ぎょうこざい", funFact:"4だんかい へんしんする！", color:"#5a1a1a", relatedIds:[] },
  { id:"godzilla-earth", type:"godzilla", roar:"godzilla-modern", name:"ゴジラ・アース", fullName:"GODZILLA アニメ三部作", year:2017, era:"アニメ", height:300, weight:100000, skill:"あかいねつせん", skillReading:"あかいねつせん", description:"アニメの ゴジラ。やまみたいに おおきい！", likes:"じきば", weak:"やまの すみっこ", funFact:"300メートルも あるよ！", color:"#1a3a2a", relatedIds:[] },
  { id:"king-of-monsters", type:"godzilla", roar:"godzilla-modern", name:"キング・オブ・モンスターズ", fullName:"ゴジラ キング・オブ・モンスターズ", year:2019, era:"モンスターバース", height:119, weight:100000, skill:"あかい バーニング ねつせん", skillReading:"あかいばーにんぐねつせん", description:"あおく もえる ゴジラ。かいじゅうの おうさま！", likes:"モスラ", weak:"つかれ", funFact:"ねつせんで そらが あかく なった！", color:"#1a3a5a", relatedIds:["king-ghidorah","mothra","rodan"] },
  { id:"godzilla-vs-kong", type:"godzilla", roar:"godzilla-modern", name:"VSコング", fullName:"ゴジラvsコング", year:2021, era:"モンスターバース", height:120, weight:100000, skill:"あおいねつせん", skillReading:"あおいねつせん", description:"コングと たたかった ゴジラ。", likes:"うみのそこ", weak:"ふとうもうの まち", funFact:"コングと なかなおりした！", color:"#3a2a3a", relatedIds:["kingkong"] },
  { id:"godzilla-minus-one", type:"godzilla", roar:"godzilla-modern", name:"ゴジラ -1.0", fullName:"ゴジラ -1.0", year:2023, era:"レイワ", height:50, weight:20000, skill:"つよい ねつせん", skillReading:"つよいねつせん", description:"いちばん あたらしい ゴジラ。", likes:"やみ", weak:"うみ", funFact:"アカデミーしょうを とったよ！", color:"#3a2a2a", relatedIds:[] },

  // === ほかの かいじゅう (29) ===
  { id:"mothra", type:"kaiju", roar:"mothra", name:"モスラ", fullName:"モスラ", year:1961, era:"ヒーロー", height:80, weight:25000, skill:"りんぷんアタック", skillReading:"りんぷんあたっく", description:"おおきな ガの かいじゅう。やさしい ヒーローだよ。", likes:"はなのみつ", weak:"ひあそび", funFact:"たまごから うまれるんだ！", color:"#e88c30", relatedIds:["showa-mothra","heisei-mothra"] },
  { id:"king-ghidorah", type:"kaiju", roar:"ghidorah", name:"キングギドラ", fullName:"キングギドラ", year:1964, era:"ライバル", height:100, weight:30000, skill:"いんりょくこうせん", skillReading:"いんりょくこうせん", description:"あたまが みっつの きんいろの りゅう。うちゅうから きた！", likes:"ちきゅうを こわすこと", weak:"チームワーク", funFact:"ゴジラの だいライバル！", color:"#d4a017", relatedIds:["showa-ghidorah","heisei-ghidorah","king-of-monsters"] },
  { id:"mechagodzilla", type:"kaiju", roar:"mecha", name:"メカゴジラ", fullName:"メカゴジラ", year:1974, era:"ロボット", height:50, weight:40000, skill:"オールレンジビーム", skillReading:"おーるれんじびーむ", description:"ロボットの かいじゅう。からだじゅうから ビームと ミサイル！", likes:"でんき", weak:"コンピューター", funFact:"ゴジラそっくりの ロボット！", color:"#7a8a99", relatedIds:["showa-mechagodzilla","heisei-mechagodzilla"] },
  { id:"rodan", type:"kaiju", roar:"rodan", name:"ラドン", fullName:"ラドン", year:1956, era:"そらの おうじゃ", height:70, weight:16000, skill:"ソニックブーム", skillReading:"そにっくぶーむ", description:"そらを とぶ かいじゅう。スピードが はやいよ！", likes:"そら", weak:"つめたいところ", funFact:"おとから うまれた！", color:"#a83232", relatedIds:["showa-ghidorah","king-of-monsters"] },
  { id:"biollante", type:"kaiju", roar:"biollante", name:"ビオランテ", fullName:"ビオランテ", year:1989, era:"しょくぶつ", height:120, weight:200000, skill:"ようかいえき", skillReading:"ようかいえき", description:"ばらの はなと ゴジラの ちからが あわさった かいじゅう！", likes:"ひかり", weak:"さむさ", funFact:"おはなだけど めっちゃ おおきい！", color:"#3d7a3d", relatedIds:["heisei-biollante"] },
  { id:"destoroyah", type:"kaiju", roar:"destroy", name:"デストロイア", fullName:"デストロイア", year:1995, era:"あくの かいじゅう", height:120, weight:80000, skill:"オキシジェンデストロイヤー", skillReading:"おきしじぇんですとろいやー", description:"あかい あくまの かいじゅう。へんしんするよ！", likes:"あく", weak:"つめたさ", funFact:"4だんかい へんしんする！", color:"#8b0000", relatedIds:["burning-godzilla"] },
  { id:"space-godzilla", type:"kaiju", roar:"space", name:"スペースゴジラ", fullName:"スペースゴジラ", year:1994, era:"うちゅう", height:120, weight:80000, skill:"コロナビーム", skillReading:"ころなびーむ", description:"うちゅうで うまれた ゴジラの コピー。そらを とぶ！", likes:"うちゅう エネルギー", weak:"クリスタル こわされる", funFact:"そらを とべる ゴジラ！", color:"#4b0082", relatedIds:["heisei-spacegodzilla"] },
  { id:"anguirus", type:"kaiju", roar:"anguirus", name:"アンギラス", fullName:"アンギラス", year:1955, era:"ともだち", height:60, weight:30000, skill:"とげとげアタック", skillReading:"とげとげあたっく", description:"せなかが とげとげの かいじゅう。ゴジラの しんゆう！", likes:"おにく", weak:"ひっくりかえされる", funFact:"ゴジラの はじめての ともだち！", color:"#996633", relatedIds:["showa-mechagodzilla","final-wars"] },
  { id:"gigan", type:"kaiju", roar:"gigan", name:"ガイガン", fullName:"ガイガン", year:1972, era:"サイボーグ", height:65, weight:25000, skill:"ばずそうチェーンソー", skillReading:"ばずそうちぇーんそー", description:"りょうてが チェーンソーの サイボーグ かいじゅう。", likes:"メカ", weak:"おしゃべりできない", funFact:"おなかにも のこぎりが ある！", color:"#1e3a5f", relatedIds:["final-wars"] },
  { id:"hedorah", type:"kaiju", roar:"hedorah", name:"ヘドラ", fullName:"ヘドラ", year:1971, era:"こうがい", height:60, weight:48000, skill:"ヘドリウム こうせん", skillReading:"へどりうむこうせん", description:"こうがいから うまれた どろどろの かいじゅう。", likes:"けむり", weak:"かわかされる", funFact:"5かい へんしんする！", color:"#3a2a3a", relatedIds:["showa-hedora"] },
  { id:"battra", type:"kaiju", roar:"mothra", name:"バトラ", fullName:"バトラ", year:1992, era:"やみの モスラ", height:90, weight:30000, skill:"プリズム ビーム", skillReading:"ぷりずむびーむ", description:"モスラの くろい きょうだい。やみの かいじゅう。", likes:"ちきゅうを まもる", weak:"ゆうじょう", funFact:"モスラと きょうだい！", color:"#1a1a3a", relatedIds:["heisei-mothra","mothra"] },
  { id:"minilla", type:"kaiju", roar:"minilla", name:"ミニラ", fullName:"ミニラ", year:1967, era:"こども", height:18, weight:6000, skill:"けむりのわっか", skillReading:"けむりのわっか", description:"ゴジラの こども！ちっちゃくて かわいいよ。", likes:"おとうさん（ゴジラ）", weak:"ひとり", funFact:"ゴジラの こどもなんだ！", color:"#5a7a3a", relatedIds:["final-wars"] },
  { id:"kamacuras", type:"kaiju", roar:"insect", name:"カマキラス", fullName:"カマキラス", year:1967, era:"むし", height:50, weight:15000, skill:"おおきな カマ", skillReading:"おおきなかま", description:"おおきな カマキリの かいじゅう。", likes:"おにく", weak:"そらから の こうげき", funFact:"ミニラを いじめた わるもの", color:"#4a5a2a", relatedIds:[] },
  { id:"kumonga", type:"kaiju", roar:"insect", name:"クモンガ", fullName:"クモンガ", year:1967, era:"むし", height:45, weight:10000, skill:"クモのいと", skillReading:"くものいと", description:"おおきな クモの かいじゅう。いとで えものを つかまえる。", likes:"むし", weak:"あつい こうげき", funFact:"あしが 8ぽん あるよ！", color:"#3a2a1a", relatedIds:["final-wars"] },
  { id:"kingkong", type:"kaiju", roar:"kong", name:"キングコング", fullName:"キングコング", year:1962, era:"ゴリラ", height:45, weight:25000, skill:"おおきな こぶし", skillReading:"おおきなこぶし", description:"とっても おおきな ゴリラ。ゴジラの ライバル！", likes:"バナナ", weak:"たかい ところ", funFact:"ニューヨークから やってきた！", color:"#4a3a2a", relatedIds:["showa-kingkong","godzilla-vs-kong"] },

  // === 新規追加怪獣 (14) ===
  { id:"jet-jaguar", type:"kaiju", roar:"mecha", name:"ジェットジャガー", fullName:"ジェットジャガー", year:1973, era:"ヒーローロボット", height:50, weight:20000, skill:"パンチ・キック", skillReading:"ぱんちきっく", description:"ゴジラの しんゆうの ヒーローロボット！おっきくなれる。", likes:"せいぎ", weak:"うらぎり", funFact:"ジャンケンに かったら おっきくなった！", color:"#c0c0c0", relatedIds:["final-wars"] },
  { id:"ebirah", type:"kaiju", roar:"ebirah", name:"エビラ", fullName:"エビラ", year:1966, era:"うみのかいじゅう", height:50, weight:23000, skill:"おおきな ハサミ", skillReading:"おおきなはさみ", description:"おっきな エビの かいじゅう。うみで くらしてる。", likes:"うみ", weak:"つまみあげ", funFact:"ハサミが ひっぱられて とれる！", color:"#cc3322", relatedIds:["final-wars"] },
  { id:"megalon", type:"kaiju", roar:"insect", name:"メガロ", fullName:"メガロ", year:1973, era:"こんちゅう", height:55, weight:40000, skill:"ドリルアーム", skillReading:"どりるあーむ", description:"てが ドリルの こんちゅうかいじゅう。", likes:"あなほり", weak:"つるつるの ところ", funFact:"うちゅうから やってきた！", color:"#6a4a2a", relatedIds:["jet-jaguar","final-wars"] },
  { id:"titanosaurus", type:"kaiju", roar:"titano", name:"チタノザウルス", fullName:"チタノザウルス", year:1975, era:"うみのきょうりゅう", height:60, weight:30000, skill:"しっぽビーム", skillReading:"しっぽびーむ", description:"うみに すむ きょうりゅうの かいじゅう。", likes:"しずかなとこ", weak:"おおきなおと", funFact:"しっぽで かぜを おこせる！", color:"#d4a0a0", relatedIds:["mechagodzilla"] },
  { id:"manda", type:"kaiju", roar:"manda", name:"マンダ", fullName:"マンダ", year:1963, era:"うみのりゅう", height:150, weight:30000, skill:"まきつき", skillReading:"まきつき", description:"おっきな うみの りゅう。ながーい からだ。", likes:"うずまき", weak:"こおり", funFact:"150メートルも あるよ！", color:"#d4a020", relatedIds:["final-wars"] },
  { id:"gabara", type:"kaiju", roar:"insect", name:"ガバラ", fullName:"ガバラ", year:1969, era:"いじめっこ", height:30, weight:5000, skill:"でんきパンチ", skillReading:"でんきぱんち", description:"いじわるな オーガの かいじゅう。でんきパンチ！", likes:"いじわる", weak:"ゆうき", funFact:"ゆめの なかにも あらわれる！", color:"#5a8a3a", relatedIds:["minilla"] },
  { id:"varan", type:"kaiju", roar:"varan", name:"バラン", fullName:"バラン", year:1958, era:"そらをとぶ", height:50, weight:15000, skill:"グライダー", skillReading:"ぐらいだー", description:"そらを とべる とかげの かいじゅう。", likes:"そら", weak:"おちる", funFact:"てと あしのあいだで グライダー！", color:"#5a4a2a", relatedIds:["final-wars"] },
  { id:"megaguirus", type:"kaiju", roar:"insect", name:"メガギラス", fullName:"メガギラス", year:2000, era:"トンボのじょおう", height:30, weight:50000, skill:"はりさし", skillReading:"はりさし", description:"おっきな あかい トンボ。じょおうさま！", likes:"エネルギーすう", weak:"ねつせん", funFact:"トンボの じょおうさま！", color:"#cc4422", relatedIds:["meganulon"] },
  { id:"frankenstein", type:"kaiju", roar:"franken", name:"フランケンシュタイン", fullName:"フランケンシュタイン対地底怪獣", year:1965, era:"きょじん", height:20, weight:5000, skill:"はやさ", skillReading:"はやさ", description:"おっきく なった フランケン。とっても はやい！", likes:"くだもの", weak:"でんき", funFact:"だんだん おおきく なるよ！", color:"#5a7a3a", relatedIds:["baragon"] },
  { id:"gorosaurus", type:"kaiju", roar:"gorosaurus", name:"ゴロザウルス", fullName:"ゴロザウルス", year:1967, era:"きょうりゅう", height:35, weight:8000, skill:"カンガルーキック", skillReading:"かんがるーきっく", description:"ティラノサウルスみたいな きょうりゅう。", likes:"おにく", weak:"おとし穴", funFact:"カンガルーキックが ひっさつわざ！", color:"#7a4a2a", relatedIds:["final-wars"] },
  { id:"zilla", type:"kaiju", roar:"zilla", name:"ジラ", fullName:"ジラ（GODZILLA 1998 改名後）", year:1998, era:"ハリウッド", height:55, weight:20000, skill:"スピード", skillReading:"すぴーど", description:"ハリウッド版の ほそい ゴジラ。とっても はやい！", likes:"さかな", weak:"ミサイル", funFact:"ファイナルウォーズで まけた！", color:"#3a5a3a", relatedIds:["hollywood-1998","final-wars"] },
  { id:"orga", type:"kaiju", roar:"orga", name:"オルガ", fullName:"オルガ", year:2000, era:"うちゅうじん", height:60, weight:60000, skill:"ジャンプ", skillReading:"じゃんぷ", description:"ゴジラの コピーになろうとした うちゅうじん。", likes:"ゴジラの ちから", weak:"ねつせん", funFact:"ゴジラに のみこまれた！", color:"#7a8a5a", relatedIds:["millennium-2000"] },
  { id:"meganulon", type:"kaiju", roar:"insect", name:"メガニューラ", fullName:"メガニューラ", year:2000, era:"こだいトンボ", height:8, weight:200, skill:"むれアタック", skillReading:"むれあたっく", description:"おっきな トンボ。むれで おそってくる！", likes:"おにく", weak:"ひとりで いるとき", funFact:"メガギラスの こども！", color:"#cc7722", relatedIds:["megaguirus"] },
  { id:"muto", type:"kaiju", roar:"muto", name:"ムートー", fullName:"M.U.T.O.", year:2014, era:"モンスターバース", height:90, weight:80000, skill:"EMPはどう", skillReading:"いーえむぴーはどう", description:"ハリウッドゴジラと たたかった くらい かいじゅう。", likes:"でんき", weak:"くび", funFact:"おすと めすで ちがう すがた！", color:"#2a2a3a", relatedIds:["hollywood-2014"] }
];

// 鳴き声タイプ→Web Audio パラメータ
const ROAR_TYPES = {
  "godzilla":         { fundamental: 50,  duration: 1.4, type: "sawtooth", sweep: [50, 90, 60], filter: 600, growl: true },
  "godzilla-burning": { fundamental: 60,  duration: 1.6, type: "sawtooth", sweep: [60, 120, 80], filter: 900, growl: true, distortion: true },
  "godzilla-modern":  { fundamental: 45,  duration: 1.8, type: "sawtooth", sweep: [45, 110, 70], filter: 700, growl: true },
  "shin-godzilla":    { fundamental: 40,  duration: 2.2, type: "square",  sweep: [40, 150, 50], filter: 1200, growl: true, distortion: true },
  "ghidorah":         { fundamental: 200, duration: 1.2, type: "sawtooth", sweep: [200, 800, 400, 1000, 300], filter: 3000, ratchet: true },
  "mothra":           { fundamental: 600, duration: 1.5, type: "triangle", sweep: [600, 1200, 800], filter: 4000, vibrato: 12 },
  "mecha":            { fundamental: 80,  duration: 1.0, type: "square",  sweep: [80, 200, 100], filter: 800, distortion: true, mechanical: true },
  "rodan":            { fundamental: 300, duration: 1.3, type: "sawtooth", sweep: [300, 900, 500], filter: 3500, ratchet: true },
  "biollante":        { fundamental: 70,  duration: 2.0, type: "sawtooth", sweep: [70, 110, 90], filter: 500, growl: true, gurgle: true },
  "destroy":          { fundamental: 100, duration: 1.5, type: "sawtooth", sweep: [100, 400, 200], filter: 2000, distortion: true },
  "space":            { fundamental: 80,  duration: 1.8, type: "sawtooth", sweep: [80, 200, 60, 300], filter: 1500, growl: true, echo: true },
  "anguirus":         { fundamental: 110, duration: 1.0, type: "sawtooth", sweep: [110, 250, 150], filter: 1200, growl: true },
  "gigan":            { fundamental: 200, duration: 1.0, type: "square",  sweep: [200, 600, 300], filter: 2500, ratchet: true, mechanical: true },
  "hedorah":          { fundamental: 90,  duration: 1.8, type: "sawtooth", sweep: [90, 130, 100], filter: 600, gurgle: true },
  "minilla":          { fundamental: 250, duration: 0.7, type: "triangle", sweep: [250, 500, 350], filter: 2500, vibrato: 8 },
  "insect":           { fundamental: 400, duration: 0.6, type: "sawtooth", sweep: [400, 1500, 800], filter: 5000, ratchet: true },
  "kong":             { fundamental: 120, duration: 1.0, type: "sawtooth", sweep: [120, 350, 200], filter: 1500, growl: true },
  "zilla":            { fundamental: 150, duration: 1.0, type: "sawtooth", sweep: [150, 400, 200], filter: 2000, growl: true },
  "ebirah":           { fundamental: 150, duration: 0.8, type: "square",  sweep: [150, 400, 200], filter: 1800, ratchet: true },
  "manda":            { fundamental: 110, duration: 1.4, type: "sawtooth", sweep: [110, 280, 180], filter: 2000, vibrato: 6 },
  "varan":            { fundamental: 280, duration: 1.0, type: "sawtooth", sweep: [280, 700, 400], filter: 3000, ratchet: true },
  "franken":          { fundamental: 130, duration: 1.2, type: "sawtooth", sweep: [130, 300, 180], filter: 1500, growl: true },
  "gorosaurus":       { fundamental: 100, duration: 1.2, type: "sawtooth", sweep: [100, 280, 160], filter: 1400, growl: true },
  "orga":             { fundamental: 80,  duration: 1.5, type: "sawtooth", sweep: [80, 250, 150], filter: 1000, growl: true, gurgle: true },
  "muto":             { fundamental: 180, duration: 1.3, type: "square",  sweep: [180, 500, 250], filter: 2500, ratchet: true, distortion: true },
  "titano":           { fundamental: 200, duration: 1.4, type: "triangle", sweep: [200, 500, 300], filter: 2200, vibrato: 7 }
};

// window参照用（const は window プロパティにならないため明示）
window.ROAR_TYPES = ROAR_TYPES;
window.KAIJU_DATA = KAIJU_DATA;
